apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-deployment2
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/awasl3/Infrastruktur
    targetRevision: HEAD
    path: ./git-ops
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: ci
  syncPolicy: 
    automated:
      prune: true
      selfHeal: true
